[cerebrium.deployment]
name = "iris-classifier"
python_version = "3.9"
gpu = "NONE"  # Using CPU for this simple model
cpu = 1.0
memory = 1.0
min_replicas = 0
max_replicas = 10

[cerebrium.dependencies]
pip = [
    "scikit-learn==1.3.0",
    "joblib==1.3.2",
    "numpy==1.24.3",
    "pandas==2.0.3"
]

[cerebrium.healthcheck]
endpoint = "/health"
timeout = 30
retries = 3